Repository micronaut-projects/micronaut-rxjava2, pull requests merged in 2023-05, with the labels that each got.

#135 [rxjava2] Update common files for branch master
  .gitattributes
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#149 [rxjava2] Update common files for branch master
  .github/workflows/files-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/release.yml
Labels: relates-to: build

#148 RxJava2 to M5
  build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.rxjava2-base.gradle
  gradle.properties
  gradle/libs.versions.toml
  rxjava2-http-server-netty/src/main/java/io/micronaut/rxjava2/server/upload/binders/MaybeBodyBinder.java
  rxjava2-http-server-netty/src/main/java/io/micronaut/rxjava2/server/upload/binders/ObservableBodyBinder.java
  rxjava2-http-server-netty/src/main/java/io/micronaut/rxjava2/server/upload/binders/RxJava2NettyBinderRegistrar.java
  rxjava2-http-server-netty/src/main/java/io/micronaut/rxjava2/server/upload/binders/SingleBodyBinder.java
  settings.gradle
Labels: type: dependency-upgrade

#150 Use new propagation API
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedCompletable.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedCompletableObserver.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedComponent.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedConnectableFlowable.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedConnectableObservable.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedFlowable.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedFlowableSubscriber.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedMaybe.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedMaybeObserver.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedObservable.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedObserver.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedParallelFlowable.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedSingle.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedSingleObserver.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedSubscriber.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumentedWrappers.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxInstrumenterFactory.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/RxJava2Instrumentation.java
  rxjava2/src/main/java/io/micronaut/rxjava2/instrument/package-info.java
Labels: type: enhancement
